### PR TITLE
STG with mixed update + other things related to the successor* functions

### PR DESCRIPTION
**Pull request by nanls**
This PR contains the following changes :

- cast string State received in  `random_successor_mixed` as dict. 

I noticed that `random_successor_mixed` does not force cast `State` to dict.
So if State is a string, PyBoolNet throw `TypeError: string indices must be integers`
when running `names = [x for x in target if target[x] != State[x]]`
This potential problem was not caught by the unit test `test_random_mixed_transition` since it is providing a `State` shaped as a dict.

The commit ce72cf6 makes the cast and now allow to run `random_successor_mixed(primes, "010")` (like in the example code that is given in the docstring)

- Remove an unused copy

In `random_successor_mixed`, there was `successor = State.copy()` while the variable `successor` was never used. Commit b01b2ee is deleting this line. 

- Change the example in the doctrings of `successor*_*`

While experimenting a bit with http://page.mi.fu-berlin.de/klarner/iBoolNet/iBoolNet.html, I realised they were no way a BN would produce the transition given in the asynchonous example. 
I modified the examples given in the successor functions (commit 313405d). 
With the example I took, 100 is a fixed point, so I used 101 for the example in `successors_asynchronous`. 

- Finally, the actual purpose of the PR is in commit 8900e9f which allows to compute a state transition graphs with the mixed update scheme.
I tested it on the following example : 
```
bnet = ("""
v1,    v2
v2,    v1 & v3
v3,    !v1 | v2
""")
```
The mixed STG of this bnet contains the following transitions : 
From 010 to :
```
110 (by updating A)
000 (B)
011 (C)
100 (AB)
111 (AC)
001 (BC)
101 (ABC)
```

This example is integrated in the docstring. 

I hope this will be helpful. Do not hesitate if you spot anything wrong. :)

### CODE REVIEW

**Comment by nanls** [comment]
Mmh, I will investigate the failing test... ^^

**Comment by nanls** [comment]
The file `PyBoolNet/Tests/Commitment.py` was deleted in 0dad95f, making the CI fail. ;)

**Comment by hklarner** [comment]
Hey,
great stuff. Two things. It seems to me that the unused `successor = State.copy()` is actually a bug. In that case I would actually like to correct it, hoping that the effect on users is small. I guess what I intended to was

```
successor = State.copy()
    for name in random.sample(names, k):
        successor[name] = target[name]
    
    return successor
```

Second, can you please send this PR to branch `develop`? I will add a point `Contributions` to the README.md that will ask all contributions to go to develop. That way I will see more easily what is the current release and what are the accumulated changes.

Thanks for your work!

**Comment by hklarner** [comment]
BTW, please take a look at

https://github.com/hklarner/PyBoolNet/issues/53

**Comment by nanls** [comment]
> It seems to me that the unused `successor = State.copy()` is actually a bug.

You are right, it is ! 

```Python
>>> import PyBoolNet
>>> primes = {
    'v1': [[{'v2': 0}], [{'v2': 1}]],
    'v2': [[{'v3': 0}, {'v1': 0}], [{'v1': 1, 'v3': 1}]],
    'v3': [[{'v1': 1, 'v2': 0}], [{'v2': 1}, {'v1': 0}]]
}
>>> stategiven = {'v1': 1, 'v2': 1, 'v3': 0}
>>> statereturned = PyBoolNet.StateTransitionGraphs.random_successor_mixed(
    primes, 
    stategiven
)
>>> stategiven
{'v1': 1, 'v2': 1, 'v3': 1} # <- stategiven has been modified
>>> statereturned
{'v1': 1, 'v2': 1, 'v3': 1}
```

I made the change you proposed in 9d9e6db.

I'm glad the bug was not affecting `primes2stg` (which casts the states to str). ;)

**Review by hklarner — APPROVED** [review]

**Comment by hklarner** [comment]
added to REALSENOTES:

- https://github.com/hklarner/PyBoolNet/commit/cf445fc0e510275d1bde796dcb0d52145408278f

**Review by nanls — COMMENTED** [review]
Ooups. I just realised the commit message of 9d9e6db was completely wrong. It should have be "Fix bug when computing a random mixed successor". Sorry about that. :(

**Comment by hklarner** [comment]
ah, I missed that too.

**Pull request merged**
